### ISSUE TITLE
Delegates orderBy parameter doesn't work

### ISSUE THREAD

**Issue by MorinelloA** [GNYIO/gny-docs#65]
[https://docs.gny.io/http/api.html#_2-4-4-get-the-list-of-delegates](https://docs.gny.io/http/api.html#_2-4-4-get-the-list-of-delegates)

The orderBy parameter for this endpoint does not appear to do anything.

Examples (all return the same order):

[https://testnet.gny.io/api/delegates?orderBy=username:desc](https://testnet.gny.io/api/delegates?orderBy=username:desc)
[https://testnet.gny.io/api/delegates?orderBy=username:asc](https://testnet.gny.io/api/delegates?orderBy=username:asc)
[https://testnet.gny.io/api/delegates?orderBy=address:desc](https://testnet.gny.io/api/delegates?orderBy=address:desc)
[https://testnet.gny.io/api/delegates?orderBy=address:asc](https://testnet.gny.io/api/delegates?orderBy=address:asc)
[https://testnet.gny.io/api/delegates?orderBy=rate:desc](https://testnet.gny.io/api/delegates?orderBy=rate:desc)

**Comment by a1300** [comment]
Thanks @MorinelloA

**Comment by a1300** [comment]
Closed by PR: #70
